### ISSUE TITLE
分布式场景下如何刷新本地的配置缓存？

### ISSUE THREAD

**Issue by xujinxiang** [caixunshi/mybatis-datalimit#2]
目前我们生产的机器是多台部署的，当更新完数据权限的配置之后，有什么办法可以直接刷新所有节点的缓存吗？

**Comment by caixunshi** [comment]
配置类中有一个refresh方法，用来刷新本机的缓存
https://github.com/caixunshi/mybatis-datalimit/blob/master/src/main/java/com/caixunshi/datalimit/config/DataLimitConfig.java
如果是多机器部署，需要自己的实现调用所有的机器，比如dubbo可以用广播调用
